apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: airlinedb
spec:
  connection:
    postgres:
      uri:
        valueFrom:
          secretKeyRef:
            key: uri
            name: mysql
  enableShellCommand: true
  immediateDeploy: true