apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealedsecrets
  namespace: default
spec:
  chart:
    spec:
      chart: sealed-secrets
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: sealedsecrets
        namespace: default
      version: 2.1.1
  interval: 5m
  values:
    replicaCount: 1